### ISSUE TITLE
Support `x-ms-client-flattening` for Body Parameters.

### ISSUE THREAD

**Issue by tjprescott** [Azure/autorest.swift#159]
Will allow service teams to control the API signature through use of the `x-ms-client-flattening` extension in Swagger. 

Support `model-flattening.json` tests.

**Passing Tests**
- [x] test_resourceFlattening_getArray (#221)
- [x] test_resourceFlattening_putArray (#221)
- [x] test_resourceFlattening_getDictionary (#221)
- [ ] test_resourceFlattening_putDictionary
- [x] test_resourceFlattening_getResourceCollection (#221)
- [ ] test_resourceFlattening_putResourceCollection
- [ ] test_resourceFlattening_getWrappedArray
- [ ] test_resourceFlattening_putWrappedArray
- [ ] test_resourceFlattening_putSimpleProduct
- [ ] test_resourceFlattening_putSimpleProductWithGroupingFlattenParameterGroup
- [ ] test_resourceFlattening_postFlattenedSimpleProduct

**Comment by tjprescott** [comment]
Closing as this is tracked in more detail by #292.
