### ISSUE TITLE
Generate OperationOptions objects and connect them to their operation signatures

### ISSUE THREAD

**Issue by tjprescott** [Azure/autorest.swift#89]
#88 adds stencil files with which to generate the per-operation Options structs, but it does not actually generate them. Work remaining:

- [x] Generate the `ClientMethodOptions.swift` file in the Options folder as per AzureStorageBlob. It will contain all of the structs, just like the `Enumerations.swift` file. (PR #102)
- [x] Modify the `OperationSnippet.stencil` file to reference the options object  and only refer to URL and body encoded parameters in the signature. (PR #102)
- [x] Modify the `OperationOptionsSnippet.stencil` to put each option in the appropriate location (query params or header). (#111)
- [x] Update the method signature comment to remove items that were relocated to the options object. (#111)

**Comment by sacheu** [comment]
Fix by #102
